### ISSUE TITLE
External Java command line tool "launcher" feature

### ISSUE THREAD

**Issue by sormuras** [forax/pro#23]
As a follow-up from #10 I'd like to discuss what's the best (read: pro) way to implement an external Java command line tool launcher. A requirement for such a feature is that it resolves tool's dependencies and executes the tool in its own VM with custom main parameters.

What I'd like to write in a "build.pro" file is something like this pseudo-code:
```
ExternalTool junit = ExternalTool.builder().withName("junit").withDependencies(list(
  "org.junit.platform:junit-platform-console-standalone:1.0.0-SNAPSHOT"
)).build()
int code = junit.start("--selectTag", "fast")
if (code == 0) code = junit.start("--selectTag", "slow")
// ... handle failures/erros/etc
```

Or with `google-java-format` as another example:
```
ExternalTool format= ExternalTool.builder().withName("format").withDependencies(list(
  "com.google.googlejavaformat:google-java-format:1.3"
)).build()
format.start(Pro.allJavaSourceFilesAsFlatStringArray())
```

On the disk, I imagine following runtime directories/files:
```
deps/
  external-tool/
    junit/ (name either generated or given by user)
      junit.platform.console.standalone.jar
   format/
      google.java.format.jar
      guava.jar
      errorprone.jar
```

Can I (re-)use the existing "runner" plugin to achive this goal?

Note: there's **no** dependency of project's modules to the external tools.

**Comment by forax** [comment]
Your external launcher is more or less pro itself.

For google.java.format, you can create a plugin just for it, formatter ?
For junit, it should be another plugin, tester?, that find all modules in the tests have a dependency on junit (on junit.platform.console.standalone ?) and run them.

You can not reuse directly the runner plugin, because i want each plugin to be independent, obviously you can cut&paste the code you want, if there is too much duplication, we will move the common part in some helpers.

**Comment by sormuras** [comment]
Started to work on `formatter` plugin: https://github.com/forax/pro/compare/master...sormuras:formatter
If I drop the "all-deps.jar" from [here](https://github.com/google/google-java-format/releases/tag/google-java-format-1.3) into pro's deps/ folder, I get:
```
[pro] registered plugins compiler, convention, formatter, linker, modulefixer, packager, resolver, runner, uberpackager
[modulefixer] multiple modules [java.xml.ws.annotation@9-ea, google.java.format@1.3-all-deps] contains package javax/annotation
```

**Comment by sormuras** [comment]
That's why I'm proposing a generic "java tool downloader, resolver and launcher" plugin that an user may configure at "script execution time" ... separated from pro itself by using its own namespace (read module path) below "deps/external-tools/<name>".

**Comment by sormuras** [comment]
Now. Having `Pro.local(action)`: how do I implement a "local tool runner"? ;)

**Comment by forax** [comment]
Before doing that, i want to experiment how to load a plugin without having its dependencies to be melt with the dependencies of another plugin.

One way to do that without local() is to do a call that will exec pro in another VM.

**Comment by forax** [comment]
Ok, i've commited https://github.com/forax/pro/commit/5dd83b07c5a174b89cfda6ea8305a347ee4dc4c4 which allows to load different plugins at runtime, each one being sandboxed
(see the runner plugin for an exemple)

**Comment by sormuras** [comment]
Great! Locally, pro builds.

Why does Travis fail: https://travis-ci.org/forax/pro/builds/225126486#L235 ?

**Comment by sormuras** [comment]
I started with a fresh "formatter" skeleton at https://github.com/forax/pro/compare/master...sormuras:plugins_formatter -- which already prints:
```
[pro] registered plugins compiler, convention, formatter, linker, modulefixer, packager, resolver, runner, uberpackager
Formatting... soon.
[pro] DONE !          elapsed time 0 ms
```
But as soon as I drop an external artifact (non modular) JAR into `{PRO_HOME}/plugins/formatter/deps`, the pro binary gets _corrupted_. `Pro` fails in static initializer in line `Plugins.getAllPlugins()` without a stacktrace.

I guess, the artifacts created by https://github.com/google/google-java-format are not "auto-module-able". Will try to use the old classpath here...

**Comment by forax** [comment]
at least
  set("compiler.moduleDependencyPath", path("deps", "plugins/formatter/../../target/main/artifact/", "plugins/formatter/../../deps"));
should be
  set("compiler.moduleDependencyPath", path("plugins/formatter/deps", "plugins/formatter/../../target/main/artifact/", "plugins/formatter/../../deps"));

also, you can put a giant try/catch around the static initializer to get the right exception

**Comment by sormuras** [comment]
Ja, that fixed it. Now, the external module is found.

Why is the "runner" line at https://github.com/forax/pro/blob/master/src/main/java/com.github.forax.pro.bootstrap/com/github/forax/pro/bootstrap/Bootstrap.java#L94 only `... path("deps", ...`

**Comment by forax** [comment]
because the runner has currently no external dependency

**Comment by sormuras** [comment]
Understood.

As I have currently more knowledge (and control) over JUnit, I started the ["tester" plugin](https://github.com/forax/pro/compare/master...sormuras:plugins_tester) in parallel. It [almost builds](https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-console-standalone/1.0.0-SNAPSHOT/), when you drop the standalone artifact from [here](https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-console-standalone/1.0.0-SNAPSHOT/) into the `plugins/tester/deps` directory manually.
Is the "resolver" not yet working with "local" or are core module/plugin dependencies not resolved by the bootstrap process?

**Comment by forax** [comment]
it should work :(
your junit.platform.console.standalone is a modular jar or not ?

**Comment by sormuras** [comment]
It's a plain old jar. You may drop [it](https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-console-standalone/1.0.0-SNAPSHOT/junit-platform-console-standalone-1.0.0-20170422.164334-149.jar) into `plugins/tester/deps` ... and the `modulefixer` injects the `module-info.class` as expected. And the `tester` plugin prints out the help text.

**Comment by forax** [comment]
Ok, the problem is in the first stage of the compiler,
that stage verifies that all modules are present fails.

instead of verbose, if you ask for debug info, it will prints all modules found by the different paths, so we may find why junit.platform.console.standalone is not found.

**Comment by sormuras** [comment]
Here you go: https://gist.github.com/sormuras/f396d02214cfb3740d1a1b9e5bcc2c3b

**Comment by forax** [comment]
The configuration seems correct, did you test locally because otherwise perhaps the jar is not uploaded to travis ?

**Comment by sormuras** [comment]
Erm, I thought the resolver would download the artifact from the configured repository on-the-fly. I didn't uploaded the JAR to github and therefore Travis didn't clone it.

Locally, with the [junit-platform-console-standalone-1.0.0-20170422.164334-149.jar](https://oss.sonatype.org/content/repositories/snapshots/org/junit/platform/junit-platform-console-standalone/1.0.0-SNAPSHOT/junit-platform-console-standalone-1.0.0-20170422.164334-149.jar) in `plugins/tester/deps` everything works. Except the exception mentioned above, that the ServiceLoader doesn't find the engine implementations...

**Comment by sormuras** [comment]
I added an local build script to tester plugin root `plugins/tester`:
```
import static com.github.forax.pro.Pro.*;

set("pro.loglevel", "verbose");
set("pro.exitOnError", true);

set("resolver.remoteRepositories", list(
  uri("https://oss.sonatype.org/content/repositories/snapshots")
))
set("resolver.dependencies", list(
  "junit.platform.console.standalone=org.junit.platform:junit-platform-console-standalone:1.0.0-SNAPSHOT"
))

set("compiler.lint", "all,-varargs,-overloads");
set("compiler.moduleDependencyPath", path("deps", "../../target/main/artifact/", "../../deps"));

run("resolver", "modulefixer", "compiler", "packager");

/exit
```

Executing **pro** in the plugin root directory shows the expected behaviour:
```
[pro] registered plugins compiler, convention, linker, modulefixer, packager, resolver, runner, uberpackager
download unresolvedArtifacts [org.junit.platform:junit-platform-console-standalone]
[resolver] resolved artifacts [org.junit.platform:junit-platform-console-standalone:1.0.0-20170422.164334-149]
[resolver] junit.platform.console.standalone (org.junit.platform:junit-platform-console-standalone:1.0.0-20170422.164334-149) downloaded from repositories
[modulefixer] fix junit.platform.console.standalone
[compiler] javac --release 9
      -Xlint:all,-varargs,-overloads
      -d target\main\exploded
      --module-source-path src\main\java
      --module-path deps;..\..\target\main\artifact;..\..\deps
src\main\java\com.github.forax.pro.plugin.tester\com\github\forax\pro\plugin\tester\ConventionFacade.java src\main\java\com.github.forax.pro.plugin.tester\com\github\forax\pro\plugin\tester\TesterConf.java src\main\java\com.github.forax.pro.plugin.tester\com\gi
thub\forax\pro\plugin\tester\TesterPlugin.java src\main\java\com.github.forax.pro.plugin.tester\module-info.java
[packager] jar --file target\main\artifact\com.github.forax.pro.plugin.tester-1.0.jar
    --module-version 1.0
    -C target\main\exploded\com.github.forax.pro.plugin.tester
[pro] DONE !          elapsed time 1.619 ms
```
The artifact is resolved by downloading and fixing it.

I guess, there's a difference between the default and local environment for the resolver plugin.

**Comment by forax** [comment]
yes, you're right, it's obvious now, you have to specify the resolver.moduleSourcePath.
  set("resolver.moduleSourcePath", path("plugins/" + name + "/src/main/java"));
otherwise, it's not resolved.

**Comment by sormuras** [comment]
Almost:
```
java.lang.IllegalStateException: no value for key dependencies
        at com.github.forax.pro.api/com.github.forax.pro.api.impl.Configs.lambda$getFromMap$2(Configs.java:113)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1137)
        at com.github.forax.pro.api/com.github.forax.pro.api.impl.Configs.getFromMap(Configs.java:111)
        at com.github.forax.pro.api/com.github.forax.pro.api.impl.Configs.lambda$proxy$4(Configs.java:274)
        at jdk.proxy1/com.sun.proxy.jdk.proxy1.$Proxy10.dependencies(Unknown Source)
        at com.github.forax.pro.plugin.resolver/com.github.forax.pro.plugin.resolver.ResolverPlugin.execute(ResolverPlugin.java:127)
        at com.github.forax.pro/com.github.forax.pro.Pro.execute(Pro.java:325)
        at com.github.forax.pro/com.github.forax.pro.Pro.runAll(Pro.java:305)
        at com.github.forax.pro/com.github.forax.pro.Pro.run(Pro.java:295)
        at com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap.lambda$compileAndPackagePlugin$4(Bootstrap.java:127)
        at com.github.forax.pro/com.github.forax.pro.Pro.local(Pro.java:270)
        at com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap.compileAndPackagePlugin(Bootstrap.java:111)
        at com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap.compileAndPackagePlugin(Bootstrap.java:107)
        at com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap.main(Bootstrap.java:87)
```

**Comment by sormuras** [comment]
Set `resolver.moduleDependencyPath = [deps]` to include "root" modules?

**Comment by sormuras** [comment]
It works:
```
      set("resolver.moduleSourcePath", path("plugins/" + name + "/src/main/java"));
      set("resolver.moduleTestPath", path("plugins/" + name + "/src/test/java"));
      set("resolver.moduleDependencyPath", path("plugins/" + name + "/deps", "plugins/" + name + "/../../target/main/artifact/", "plugins/" + name + "/../../deps"));
```

**Comment by sormuras** [comment]
The "zero test engine found" problem is a bug in JUnit 5 using the wrong class loader:
```
ServiceLoader.load(TestEngine.class)
  loader = jdk.jshell.execution.DefaultLoaderDelegate$RemoteClassLoader@4b952a2d
ServiceLoader.load(TestEngine.class, getClass().getClassLoader())
  loader = jdk.internal.loader.Loader@42607a4f
org.junit.jupiter.engine.JupiterTestEngine@fa36558
org.junit.vintage.engine.VintageTestEngine@672872e1
ServiceLoader.load(TestEngine.class, TestEngine.class.getClassLoader())
  loader = jdk.internal.loader.Loader@42607a4f
org.junit.jupiter.engine.JupiterTestEngine@484970b0
org.junit.vintage.engine.VintageTestEngine@4470f8a6
ServiceLoader.load(ModuleLayer layer, TestEngine.class) // TODO
```

**Comment by forax** [comment]
Or i can set the contextClassLoader when pro executes a plugin ?

**Comment by sormuras** [comment]
Mh, a plugin might rely on its own class loader hierarchy.

But, inside "TesterPlugin#execute(...)" the line `Thread.currentThread().setContextClassLoader(TestEngine.class.getClassLoader());` did the trick.

Mh, feels not so good...

**Comment by sormuras** [comment]
Initial two ✔️ sighted at https://travis-ci.org/sormuras/pro/builds/225549729

Now pro needs some Jupiter tests... ;)

**Comment by sormuras** [comment]
`6 tests successful` at https://travis-ci.org/forax/pro/builds/225895306#L291

**Comment by forax** [comment]
I thinkyou should wrap it into a try/finally,
otherwise your classloader hierarchy will be visible by the other plugins.

Thread currentThread = Thread.currentThread();
ClassLoader oldContext = currentThread.getContextClassLoader();
try {
   currentThread.setContextClassLoader(...);
   ...
} finally {
  currentThread.setContextClassLoader(oldContext);  // restore the context
}

**Comment by sormuras** [comment]
Closing this issue as solved: `./plugins`
